#!/usr/bin/env bash
set -euo pipefail

# Upgrade the persisted /mnt/set-wandb-api-key.sh so it works for non-interactive
# sessions by writing/updating ~/.netrc for api.wandb.ai.
#
# This script is safe to run multiple times (idempotent).
# It does NOT print the API key.

TARGET="/mnt/set-wandb-api-key.sh"

if [[ ! -f "$TARGET" ]]; then
  echo "ERROR: missing $TARGET" >&2
  exit 2
fi

python3 - <<'PY'
from __future__ import annotations

import os
import shutil
import time
from pathlib import Path

target = Path('/mnt/set-wandb-api-key.sh')
text = target.read_text()

is_autogen = 'AUTOGENERATED_WANDB_NETRC' in text
buggy_newlines = "write_text('\\\\n'.join" in text or "write_text(\"\\\\n\".join" in text

# If it's already upgraded and not buggy, nothing to do.
if is_autogen and not buggy_newlines:
    raise SystemExit(0)

backup = target.with_name(f'{target.name}.bak-{time.strftime("%Y%m%d-%H%M%S")}')
shutil.copy2(target, backup)
os.chmod(backup, 0o600)

key_lines: list[str] = []
for line in text.splitlines():
    s = line.strip()
    if 'WANDB_API_KEY' not in s:
        continue
    if s.startswith('export WANDB_API_KEY='):
        key_lines.append(s)

if not key_lines:
    raise SystemExit('ERROR: could not find export WANDB_API_KEY=... in /mnt/set-wandb-api-key.sh')

# Keep exactly one key export line to avoid accumulating multiple writers.
payload = key_lines[0] + "\n"

py_snippet = r"""import os
import pathlib
import re

key = os.environ.get('WANDB_API_KEY')
if not key:
    raise SystemExit(0)

netrc_path = pathlib.Path.home() / '.netrc'
text = netrc_path.read_text() if netrc_path.exists() else ''
# Normalize past buggy writers that stored literal "\\n" sequences.
text = text.replace('\\n', '\n')
lines = text.splitlines()

out = []
i = 0
machine_re = re.compile(r'^\\s*machine\\s+\\S+')
target_re = re.compile(r'^\\s*machine\\s+api\\.wandb\\.ai\\b')

while i < len(lines):
    if target_re.match(lines[i]) or 'api.wandb.ai' in lines[i]:
        i += 1
        while i < len(lines) and not machine_re.match(lines[i]):
            i += 1
        continue
    out.append(lines[i])
    i += 1

out.extend([
    'machine api.wandb.ai',
    '  login user',
    f'  password {key}',
])

netrc_path.write_text('\n'.join(out).rstrip() + '\n')
netrc_path.chmod(0o600)
"""


upgrade = (
    "#!/usr/bin/env bash\n"
    "set -euo pipefail\n\n"
    "# AUTOGENERATED_WANDB_NETRC\n\n"
    + payload
    + "\npython3 - <<'PY'\n"
    + py_snippet
    + "\nPY\n\n"
    + "unset WANDB_API_KEY\n"
)

target.write_text(upgrade)
os.chmod(target, 0o600)
PY

# Verify without printing secrets
bash "$TARGET"
python3 - <<'PY'
import netrc

n = netrc.netrc()
auth = n.authenticators('api.wandb.ai')
if not auth:
    raise SystemExit(2)
print('WANDB_NETRC_OK')
PY
